# -*- coding: utf-8 -*-
"""HasBrainTumerOrNot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110sFBISzcWHV58By7tIqOQw9n_BQ4Nir

## Data Downloading
"""


import zipfile
zip_ref = zipfile.ZipFile('/content/brain-tumor-mri-dataset.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

"""## Importing Libraries"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import cv2
import random
from PIL import Image, ImageEnhance

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.preprocessing.image import load_img
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, BatchNormalization, Dropout
from keras.applications.vgg16 import VGG16
from keras.optimizers import Adam
from keras.applications.vgg16 import preprocess_input
from sklearn.utils import shuffle

train_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/Training',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (256, 256)
)

for labels in train_ds.class_names:
  print(labels)

train_path = []
train_label = []

base_dir = '/content/Training'
class_names = train_ds.class_names # Get class names from the dataset

for i, class_name in enumerate(class_names):
  class_dir = os.path.join(base_dir, class_name)
  for image_name in os.listdir(class_dir):
    train_path.append(os.path.join(class_dir, image_name))
    train_label.append(i) # Assign integer label corresponding to class_name

train_label, train_path = shuffle(train_label, train_path)

train_path

train_label

test_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/Testing',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (256, 256)
)

test_path = []
test_label = []

base_test = '/content/Testing'
class_names = test_ds.class_names

for i, class_name in enumerate(class_names):
  class_dir = os.path.join(base_test, class_name)
  for image_name in os.listdir(class_dir):
    test_path.append(os.path.join(class_dir, image_name))
    test_label.append(i)

test_label, test_path = shuffle(test_label, test_path)

test_path

test_label

"""## Data Visualization"""

import matplotlib.pyplot as plt

random_ten = random.sample(range(len(train_path)), 10)

random_ten

fig, plt.axes = plt.subplots(2, 5, figsize=(15, 7))
axes = plt.axes.ravel()

class_names = train_ds.class_names

for i,idx in enumerate(random_ten):
  img = cv2.imread(train_path[idx])
  img = Image.open(train_path[idx])
  img = img.resize((256, 256))
  axes[i].imshow(img)
  axes[i].axis("off")
  axes[i].set_title(f"Label - {class_names[train_label[idx]]}")

plt.tight_layout()
plt.show()

random_ten_new = random.sample(range(len(train_path)), 10)

fig_new, plt_axes_new = plt.subplots(2, 5, figsize=(15, 7))
axes_new = plt_axes_new.ravel()

class_names = train_ds.class_names

for i, idx in enumerate(random_ten_new):
  img = Image.open(train_path[idx])
  img = img.resize((256, 256))
  axes_new[i].imshow(img)
  axes_new[i].axis("off")
  axes_new[i].set_title(f"Label - {class_names[train_label[idx]]}")

plt.tight_layout()
plt.show()

from collections import Counter

label_counts = Counter(train_label)

class_names = train_ds.class_names

print("Counts of each label type in the training dataset:")
for label_id, count in label_counts.items():
  print(f"  {class_names[label_id]}: {count} images")

label_counts2 = Counter(test_label)

class_names2 = test_ds.class_names

print("Counts of each label type in the testing dataset:")
for label_id, count in label_counts2.items():
  print(f"  {class_names2[label_id]}: {count} images")

import matplotlib.pyplot as plt
import pandas as pd

# Data from training
train_labels_df = pd.DataFrame({
    'Class': [class_names[label_id] for label_id in label_counts.keys()],
    'Count': list(label_counts.values())
}).sort_values(by='Class').reset_index(drop=True)

# Data from testing set
test_labels_df = pd.DataFrame({
    'Class': [class_names2[label_id] for label_id in label_counts2.keys()],
    'Count': list(label_counts2.values())
}).sort_values(by='Class').reset_index(drop=True)

plt.figure(figsize=(12, 7))
plt.plot(train_labels_df['Class'], train_labels_df['Count'], marker='o', linestyle='-', color='skyblue', label='Training Data')
plt.plot(test_labels_df['Class'], test_labels_df['Count'], marker='x', linestyle='--', color='salmon', label='Testing Data')

plt.title('Distribution of Brain Tumor Types in Training and Testing Datasets')
plt.xlabel('Tumor Type')
plt.ylabel('Number of Images')
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')
plt.legend()
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(15, 7))

# Pie chart for Training Data
axes[0].pie(train_labels_df['Count'], labels=train_labels_df['Class'], autopct='%1.1f%%', startangle=90, colors=plt.cm.Paired.colors)
axes[0].set_title('Training Data Class Distribution')
axes[0].axis('equal')

# Pie chart for Testing Data
axes[1].pie(test_labels_df['Count'], labels=test_labels_df['Class'], autopct='%1.1f%%', startangle=90, colors=plt.cm.Paired.colors)
axes[1].set_title('Testing Data Class Distribution')
axes[1].axis('equal')

plt.tight_layout()
plt.show()

"""## Data Preprocessing"""

IMAGE_SIZE = 256

# Image Augmentation function
def augment_image(image):
    image = Image.fromarray(np.uint8(image))
    image = ImageEnhance.Brightness(image).enhance(random.uniform(0.8, 1.2))
    image = ImageEnhance.Contrast(image).enhance(random.uniform(0.8, 1.2))
    image = np.array(image) / 255.0
    return image

# Load images and apply augmentation
def open_images(paths):
    images = []
    for path in paths:
        image = load_img(path, target_size=(IMAGE_SIZE, IMAGE_SIZE))
        image = augment_image(image)
        images.append(image)
    return np.array(images)

# Encoding labels (convert label names to integers)
def encode_label(labels):
    class_names_list = train_ds.class_names
    encoded = [class_names_list.index(label) for label in labels]
    return np.array(encoded)

# Data generator for batching
def datagen(paths, labels, batch_size=12, epochs=1):
    for _ in range(epochs):
        for i in range(0, len(paths), batch_size):
            batch_paths = paths[i:i + batch_size]
            batch_images = open_images(batch_paths)
            batch_labels = np.array(labels[i:i + batch_size]) # Convert labels to a NumPy array
            yield batch_images, batch_labels

"""## Model Training"""

IMAGE_SIZE = 256
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3))

for layers in base_model.layers:
  layers.trainable = False

base_model.layers[-2].trainable = True
base_model.layers[-3].trainable = True
base_model.layers[-4].trainable = True

from keras.layers import Input

model = Sequential()
model.add(Input(shape=(IMAGE_SIZE, IMAGE_SIZE, 3)))
model.add(base_model)
model.add(Flatten())
model.add(Dropout(0.3))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(len(train_ds.class_names), activation='softmax'))

model.compile(optimizer=Adam(learning_rate=0.0001), loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

batch_size = 36
steps = int(len(train_path) / batch_size)
epochs = 5

model.summary()

history = model.fit(datagen(train_path, train_label, batch_size=batch_size, epochs=epochs),epochs=epochs, steps_per_epoch=steps)

"""## Model Visualization"""

plt.figure(figsize=(15, 7))
plt.grid(True)
plt.plot(history.history['sparse_categorical_accuracy'], '.g-', linewidth=2)
plt.plot(history.history['loss'], '.r-', linewidth=2)
plt.title('Model Training History')
plt.xlabel('epoch')
plt.xticks([x for x in range(epochs)])
plt.legend(['Accuracy', 'Loss'], loc='upper left', bbox_to_anchor=(1, 1))
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import seaborn as sns
from sklearn.preprocessing import label_binarize
from keras.models import load_model
import numpy as np

# 1. Prediction on test data
test_images = open_images(test_path)
test_labels_encoded = test_label

test_predictions = model.predict(test_images)

# 2. Classification Report
print("Classification Report:")
print(classification_report(test_labels_encoded, np.argmax(test_predictions, axis=1)))

# 3. Confusion Matrix
conf_matrix = confusion_matrix(test_labels_encoded, np.argmax(test_predictions, axis=1))

plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues", xticklabels=train_ds.class_names, yticklabels=train_ds.class_names) # Corrected train_dir to train_ds.class_names
plt.title("Confusion Matrix")
plt.xlabel("Predicted Labels")
plt.ylabel("True Labels")
plt.show()

# 4. ROC Curve and AUC
test_labels_bin = label_binarize(test_labels_encoded, classes=np.arange(len(train_ds.class_names))) # Corrected train_dir
test_predictions_bin = test_predictions

fpr, tpr, roc_auc = {}, {}, {}
for i in range(len(train_ds.class_names)):
    fpr[i], tpr[i], _ = roc_curve(test_labels_bin[:, i], test_predictions_bin[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot ROC curve
plt.figure(figsize=(10, 8))
for i in range(len(train_ds.class_names)):
    plt.plot(fpr[i], tpr[i], label=f'Class {i} (AUC = {roc_auc[i]:.2f})')

plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend(loc="lower right")
plt.show()

"""## Model Saving"""

model.save('model.h5')

from keras.models import load_model
model = load_model("model.h5")

"""## System Configuration"""

from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import load_img

class_labels = ['pituitary', 'glioma', 'notumor', 'meningioma']

def detect_and_display(img_path, model, image_size=128):

    try:
        # Load and preprocess the image
        img = load_img(img_path, target_size=(image_size, image_size))
        img_array = img_to_array(img) / 255.0
        img_array = np.expand_dims(img_array, axis=0)

        # Make a prediction
        predictions = model.predict(img_array)
        predicted_class_index = np.argmax(predictions, axis=1)[0]
        confidence_score = np.max(predictions, axis=1)[0]

        # Determine the class
        if class_labels[predicted_class_index] == 'notumor':
            result = "No Tumor"

        else:
            result = f"Tumor: {class_labels[predicted_class_index]}"

        # Display the image with the prediction
        plt.imshow(load_img(img_path))
        plt.axis('off')
        plt.title(f"{result}")
        plt.show()

    except Exception as e:
        print("Error processing the image:", str(e))

img_path = '/content/MRI.jpg'
detect_and_display(img_path, model, image_size=IMAGE_SIZE) # Pass the correct IMAGE_SIZE

img_path = '/content/Tumor.jpg'
detect_and_display(img_path, model, image_size=IMAGE_SIZE)

from google.colab import files

files.download('model.h5')